### ISSUE TITLE
parser unquoted attributes too?

### ISSUE THREAD

**Issue by Pomax** [mozilla/slowparse#15]
Not sure how prevalent this is in the wild, but we may need to support this for page remixing. It might actually not be too much work.

**Comment by toolness** [comment]
True dat, though for now I'd like to see if the learning team (or user testing) raises concerns about this, like they did w/ self-closing void tags in #23. I honestly didn't know that unquoted attributes were even legal until a few months ago--though my main concern with adding support for this is just that we may end up providing more confusing help to users if we assume this. For instance, HTML like this:

``` html
<p class=super cool>hi there</p>
```

might get successfully parsed without raising any red flags to the user (leaving them to get confused later when their CSS doesn't apply), or it might provide the unhelpful suggestion that `cool` is an unrecognized boolean attribute, while in fact the suggestion that the user _probably_ needs is that they need to put quotes around their attribute value--which is what our parser currently suggests.
