### ISSUE TITLE
pasting code in editor does not stretch with scrollbar, but keeps it weirdly sized

### ISSUE THREAD

**Issue by Pomax** [mozilla/slowparse#29]
pasting code is important, and should trigger a reflow instead of whatever it's doing now.

**Comment by toolness** [comment]
The `refresh()` method might help w/ this. From the [CodeMirror manual](http://codemirror.net/doc/manual.html#api):

> If your code does something to change the size of the editor element (window resizes are already listened for), or unhides it, you should probably follow up by calling this method to ensure CodeMirror is still looking as intended.

**Comment by toolness** [comment]
Moving this to [friendlycode issue #2](https://github.com/toolness/friendlycode/issues/2).
