### ISSUE TITLE
"Missing block closer or next property:value; pair following @-moz-keyframes x" w/ CSS animations

### ISSUE THREAD

**Issue by toolness** [mozilla/slowparse#42]
From [this tweet](https://twitter.com/BJMNS/status/213806647460626432).

We need to bust up a test case and fix it.

**Comment by Pomax** [comment]
what is @-moz-keyframes? Is that legal CSS or a browser-hack?

**Comment by stenington** [comment]
[Here's an example](https://thimble.webmaker.org/p/ric/edit). It works great in the preview and when published, but the editor complains.

**Comment by Pomax** [comment]
hm, so it's a vendor prefixed version of @keyframes... we may want to consider adding https://github.com/LeaVerou/prefixfree to prevent this for pretty much every "sexy and new" CSS thing to hosted pages. We don't do vendor prefixes in slowparse at all at the moment, so it'd have to be @keyframes at the least slowparse is also not aware of some of the new @instructionset keywords, so I'll file an issue for that to start with - https://github.com/toolness/slowparse/issues/48
