### ISSUE TITLE
add in @instruction parsing for newer CSS constructions (keyframes, etc)

### ISSUE THREAD

**Issue by Pomax** [mozilla/slowparse#48]
There's a number of @instruction selector replacements and prefixes that slowparse does not understand right now.

**Comment by Pomax** [comment]
stems from #42

**Comment by toolness** [comment]
It looks like Jess is already making wireframes of learning projects that will require us to fix this! http://www.flickr.com/photos/jessicaklein/7727412006/

**Comment by Pomax** [comment]
Testing with 

```
      @-moz-keyframes myfirst {  
        from {background: red;}
        to {background: yellow;}
      }
```

throws up errors, due to the from() and to() notations - basically because it's not a normal CSS block, slowparse flags it. A list of @instructions that have "normal" css breaking syntax is probably required to ensure we run through the correct parsing.
