### ISSUE TITLE
incorrect 'boolean attribute' report

### ISSUE THREAD

**Issue by Pomax** [mozilla/slowparse#6]
using the following text:

```
<h2><span start=</h2>
```

reports an unsupported boolean attribute type, even though the = should have made the parser switch to string-content attribute detection and complain there's quotes missing.

this only happens if &lt;/h2&gt; is present.

**Comment by toolness** [comment]
Hmm, either 5912f6520adee13b5a5e21014e1a3a643e8c439c or an earlier commit fixed this. Added a regression test in 3488d44 and closing the bug.
