### ISSUE TITLE
Possibly in scope: message about malformed color property

### ISSUE THREAD

**Issue by pamelafox** [mozilla/slowparse#69]
I notice many KA students are typing rgb and then a space before the (, which is invalid CSS. Example:

```
        #summer {color: rgb (176, 42, 176);}
        #winter {color: rgb (43, 204, 196);}
```

In Chrome, the little in-dev-tools-validator notices the issue and crosses it out, with "Unknown property value."

Would that level of warning be in scope for slowparse?

Example:

**Comment by Pomax** [comment]
hm, that would require building validation rules for every known CSS property, which is probably out of scope, _but_ there might already be an npm module out there that does that for us, so it would be possible to give slowparse some "if you have a CSS validator, ask it whether the found combination of property + value is legal" without writing the validation code ourselves.

**Comment by Pomax** [comment]
I'm going to close this, and point to the docs on how to add your own additional parsers for this. See https://github.com/mozilla/slowparse#using-slowparse for the updated docs that also explain how to add additional parsing during runs.
