### ISSUE TITLE
A message that could be improved with missing equal signs for attributes

### ISSUE THREAD

**Issue by pamelafox** [mozilla/slowparse#73]
Given code:

```
<!DOCTYPE HTML>
<html>
    <head>
        <title>Challenge: A picture-perfect trip</title>
        <meta charset="utf-8">
    </head>
    <body>
        <h1>The perfect trip</h1>

        <p>I would see scenes like oceans</p> <img src="https://www.kasandbox.org/programming-images/landscapes/beach-in-hawaii.png" alt="beach in hawaii" width="207">

        <p>And animals like sharks</p>
        <img src="https://www.kasandbox.org/programming-images/animals/shark.png" alt="shark swimming in the oceans" width="207">

        <p>And eat food like fresh grilled snapper</p>
        <img src="https://www.kasandbox.org/programming-images/food/fish_grilled-snapper.png" alt="fresh grilled snapper"
  width "207">


    </body>
</html>
```

It says:
"The opening <img> tag here doesn't end with a >."

However, if it said "an attribute name should be followed by an equal sign", that would be more accurate.
Not sure how possible that is, but the current one does confuse.

**Comment by pamelafox** [comment]
Related:

``` html
<!DOCTYPE HTML>
<html>
    <head>
        <title>Challenge: A picture-perfect trip</title>
        <meta charset="utf-8">
    </head>
    <body>
        <img src="https://www.kasandbox.org/programming-images/food/fish_grilled-snapper.png" alt="fresh grilled snapper"
 "207">

    </body>
</html>

```

**Comment by Pomax** [comment]
another nice find. should be able to start working on these issues wed/thu

**Comment by Pomax** [comment]
looking at this a bit closely, technically `width "207"` is only wrong on the `"207"` part, since HTML5 attributes are allowed to not have a value assignment. I'll create a test case for detached `"..."` strings so that we can report the correct error on it.

**Comment by Pomax** [comment]
landed in https://github.com/mozilla/slowparse/commit/21282ef57fb6130666b7db15731ff0206fc7f756 as a new error, https://github.com/mozilla/slowparse/blob/gh-pages/src/ParseErrorBuilders.js#L167 (localised string: http://mozilla.github.io/slowparse/locale/#UNBOUND_ATTRIBUTE_VALUE once the gh-pages branch rebuilds)
