### ISSUE TITLE
vendor-prefixed CSS isn't recognized

### ISSUE THREAD

**Issue by toolness** [mozilla/slowparse#8]
It might be cool if folks could use vendor-prefixed CSS, or at least some nice subset of it like `-o-transform` and `-moz-transition`. Alternatively, a somewhat sneaky thing to do might be to take any `transform` declarations and magically turn them into their vendor-specific equivalents after parsing...

Either way, not that high a priority I guess.

**Comment by Pomax** [comment]
vendor-prefixed CSS is really "experimental land". we can turn property parsing into a two stage process, where we parse for a vendor prefix if the property name starts with -, although I'm not sure if suggesting vendor-specific CSS will be a good idea?

**Comment by toolness** [comment]
It seems that #22 is a fix for this.

**Comment by Pomax** [comment]
it is indeed, let me add a unit test and repush.

**Comment by toolness** [comment]
Fixed by #8!

**Comment by toolness** [comment]
Oops. I mean, fixed by #22.
