### ISSUE TITLE
Error when using slashes in CSS class names

### ISSUE THREAD

**Issue by pamelafox** [mozilla/slowparse#82]
Reported from Khan Academy user:
https://www.khanacademy.org/computer-programming/css-character-escaping/6037177738330112

Apparently slashes are valid CSS class names (it takes a lot of digging to verify this, but it seems to be the case). Slowparse does not like them, however, and reports 'Missing block opener after ..'.

Replicate in Thimble with this code:

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>CSS Character Escaping</title>
        <style>
            .\. {
                color: red;
            }
            .\! {
                color: green;
            }
            .\, {
                color: blue;
            }
            .\; {
                color: purple;
            }
            .\{ {
                color: purple;
            }
        </style>
    </head>
    <body>
        <p class=".">My class name is "."</p>
        <p class="!">My class name is "!"</p>
        <p class=",">My class name is ","</p>
        <p class=";">My class name is ";"</p>
        <p class="{">My class name is "{"</p>
    </body>
</html>
```

**Comment by Pomax** [comment]
In this case I'm tempted to leave this in: Slowparse tries to do the right thing, but it's designed primarily to prefer "good HTML5 code" over "technically correct, but super unfriendly for people to try to make sense of", and slashes in the classes definitely falls in the "technically-allowed, but please never actually do this for reals" category. 

That said, if this is important enough for you to write an initial fix with a PR that widens the class name acceptance, I'll be happy to help test/review it and get it landed.

**Comment by pamelafox** [comment]
That makes sense to me. I was certainly surprised to find out that it was actually valid CSS. I'll close this.
